### ISSUE TITLE
Using Oauth2.Builder gives NoSuchMethodError for com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.<init>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dulkith/google-api-java-client#894]
```
Version of google-api-java-client (e.g. 1.15.0-rc)?
1.17.0-rc

Java environment (e.g. Java 6, Android 2.3, App Engine)?
Java 6

Describe the problem.
After Upgrading from 1.13 to 1.17 I got this issue when using the 
Oauth2.Builder to get the user info

How would you expect it to be fixed?
Is something that has to be done different in the flow? I couldn't figure what

```

Original issue reported on code.google.com by `casper...@gmail.com` on 14 Jul 2014 at 7:07
